export enum BookingStatus {
    NOT_INITIATED = "NOT_INITIATED",
    PAYMENT_PENDING = "PAYMENT_PENDING",
    READY = "READY",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    CANCELED = "CANCELED",
}
