export enum BookingStatus {
    PAYMENT_PENDING = "PAYMENT_PENDING",
    CONFIRMED = "CONFIRMED",
    CANCELED = "CANCELED",
    IN_PROGRESS = "IN_PROGRESS",
    OVERDUE = "OVERDUE",
    CONCLUDED = "CONCLUDED",
}
