export enum DressStatus {
  AVAILABLE = "AVAILABLE",
  OUT_OF_STOCK = "OUT_OF_STOCK",
  BOOKED = "BOOKED",
  PICKED_UP = "PICKED_UP",
  RETURNED = "RETURNED",
  IN_WASH = "IN_WASH",
  DAMAGED = "DAMAGED",
}

export enum PurseStatus {
  AVAILABLE = "AVAILABLE",
  OUT_OF_STOCK = "OUT_OF_STOCK",
  BOOKED = "BOOKED",
  PICKED_UP = "PICKED_UP",
  RETURNED = "RETURNED",
  DAMAGED = "DAMAGED",
}

export enum JewelryStatus {
  AVAILABLE = "AVAILABLE",
  OUT_OF_STOCK = "OUT_OF_STOCK",
}
